import { z } from "zod";

export const Method = {
  PING: "ping",
  WORLD_GET: "world.get",
  DOCUMENTS_LIST: "documents.list",
  DOCUMENTS_GET: "documents.get",
  DOCUMENTS_SEARCH: "documents.search",
  DOCUMENTS_FIND_REFS: "documents.find_references",
  DOCUMENTS_REFRESH_LABELS: "documents.refresh_labels",
  DOCUMENTS_CREATE: "documents.create",
  DOCUMENTS_UPDATE: "documents.update",
  DOCUMENTS_DELETE: "documents.delete",
  EMBEDDED_CREATE: "embedded.create",
  EMBEDDED_UPDATE: "embedded.update",
  EMBEDDED_DELETE: "embedded.delete",
  COMPENDIUM_LIST: "compendium.list",
  COMPENDIUM_SEARCH: "compendium.search",
  COMPENDIUM_IMPORT: "compendium.import",
  COMPENDIUM_EXPORT: "compendium.export",
  COMPENDIUM_CREATE: "compendium.create",
  COMPENDIUM_DELETE: "compendium.delete",
  FOLDERS_CREATE: "folders.create",
  FOLDERS_MOVE: "folders.move",
  MESSAGES_CREATE: "messages.create",
  SCENE_ACTIVE: "scene.active",
  SCENE_ACTIVATE: "scene.activate",
  TOKEN_PLACE: "token.place",
  TOKEN_UPDATE: "token.update",
  DICE_ROLL: "dice.roll",
  TABLE_DRAW: "table.draw",
  COMBAT_CREATE: "combat.create",
  COMBAT_ADD: "combat.add",
  COMBAT_ROLL_INITIATIVE: "combat.roll_initiative",
  COMBAT_ADVANCE: "combat.advance",
  FILES_BROWSE: "files.browse",
  FILES_UPLOAD: "files.upload",
  ACTOR_CREATE: "actor.create",
  ACTOR_GRANT_ITEM: "actor.grant_item",
  CONDITIONS_LIST: "conditions.list",
  ACTOR_TOGGLE_CONDITION: "actor.toggle_condition",
  ACTOR_ROLL_DATA: "actor.roll_data",
  ACTOR_ASSIGN: "actor.assign",
  ACTOR_APPLY_DAMAGE: "actor.apply_damage",
  ACTOR_APPLY_HEALING: "actor.apply_healing",
  DND5E_APPLY_DAMAGE: "dnd5e.apply_damage",
  DND5E_APPLY_HEALING: "dnd5e.apply_healing",
  DND5E_ROLL: "dnd5e.roll",
  DND5E_REST: "dnd5e.rest",
  DND5E_ACTOR_SUMMARY: "dnd5e.actor_summary",
  TABLE_CREATE: "table.create",
  TABLE_ADD_RESULTS: "table.add_results",
  PLAYLIST_PLAY: "playlist.play",
  PLAYLIST_STOP: "playlist.stop",
  PLAYLIST_PLAY_SOUND: "playlist.play_sound",
  MESSAGES_LIST: "messages.list",
  DICE_ROLL_TO_CHAT: "dice.roll_to_chat",
  DOCUMENTS_DUPLICATE: "documents.duplicate",
  PRESENT_SHOW: "present.show_to_players",
  PRESENT_PULL: "present.pull_to_scene",
  PRESENT_PING: "present.ping",
  SCENE_UPDATE: "scene.update",
  SCENE_RESET_FOG: "scene.reset_fog",
  COMBAT_SET_INITIATIVE: "combat.set_initiative",
  COMBAT_REMOVE: "combat.remove_combatant",
  MACRO_EXECUTE: "macro.execute",
  STATUS_GET: "status.get",
  CARDS_DEAL: "cards.deal",
  CARDS_DRAW: "cards.draw",
  CARDS_SHUFFLE: "cards.shuffle",
  CARDS_PASS: "cards.pass",
  CARDS_RESET: "cards.reset",
  TIME_ADVANCE: "time.advance",
  TIME_SET: "time.set",
  WALLS_DRAW: "scene.draw_walls",
  SCENE_CREATE: "scene.create",
  DOOR_TOGGLE: "scene.toggle_door",
  LIGHT_PLACE: "scene.place_light",
  NOTE_PLACE: "scene.place_note",
  TEMPLATE_PLACE: "scene.place_template",
  DND5E_SPELL_SLOTS: "dnd5e.spell_slots",
  DND5E_CURRENCY: "dnd5e.currency",
  DND5E_AWARD_XP: "dnd5e.award_xp",
  DND5E_HIT_DICE: "dnd5e.hit_dice",
  DND5E_DEATH_SAVES: "dnd5e.death_saves",
  DND5E_CONCENTRATION: "dnd5e.concentration",
  DND5E_USE_ITEM: "dnd5e.use_item",
  DND5E_ITEM_ROLL: "dnd5e.item_roll",
  PLAYLIST_CREATE: "playlist.create",
  PLAYLIST_ADD_SOUNDS: "playlist.add_sounds",
  COMBATANT_DAMAGE: "combat.damage_combatant",
  COMBATANT_UPDATE: "combat.update_combatant",
  COMBATANT_CONDITION: "combat.combatant_condition",
  MODULES_LIST: "modules.list",
  MODULE_GET: "modules.get",
  SETTINGS_LIST: "settings.list",
  SETTING_GET: "settings.get",
  SETTING_SET: "settings.set",
} as const;

export type Method = (typeof Method)[keyof typeof Method];

export const methodSchema = z.enum([
  Method.PING,
  Method.WORLD_GET,
  Method.DOCUMENTS_LIST,
  Method.DOCUMENTS_GET,
  Method.DOCUMENTS_SEARCH,
  Method.DOCUMENTS_FIND_REFS,
  Method.DOCUMENTS_REFRESH_LABELS,
  Method.DOCUMENTS_CREATE,
  Method.DOCUMENTS_UPDATE,
  Method.DOCUMENTS_DELETE,
  Method.EMBEDDED_CREATE,
  Method.EMBEDDED_UPDATE,
  Method.EMBEDDED_DELETE,
  Method.COMPENDIUM_LIST,
  Method.COMPENDIUM_SEARCH,
  Method.COMPENDIUM_IMPORT,
  Method.COMPENDIUM_EXPORT,
  Method.COMPENDIUM_CREATE,
  Method.COMPENDIUM_DELETE,
  Method.FOLDERS_CREATE,
  Method.FOLDERS_MOVE,
  Method.MESSAGES_CREATE,
  Method.SCENE_ACTIVE,
  Method.SCENE_ACTIVATE,
  Method.TOKEN_PLACE,
  Method.TOKEN_UPDATE,
  Method.DICE_ROLL,
  Method.TABLE_DRAW,
  Method.COMBAT_CREATE,
  Method.COMBAT_ADD,
  Method.COMBAT_ROLL_INITIATIVE,
  Method.COMBAT_ADVANCE,
  Method.FILES_BROWSE,
  Method.FILES_UPLOAD,
  Method.ACTOR_CREATE,
  Method.ACTOR_GRANT_ITEM,
  Method.CONDITIONS_LIST,
  Method.ACTOR_TOGGLE_CONDITION,
  Method.ACTOR_ROLL_DATA,
  Method.ACTOR_ASSIGN,
  Method.ACTOR_APPLY_DAMAGE,
  Method.ACTOR_APPLY_HEALING,
  Method.DND5E_APPLY_DAMAGE,
  Method.DND5E_APPLY_HEALING,
  Method.DND5E_ROLL,
  Method.DND5E_REST,
  Method.DND5E_ACTOR_SUMMARY,
  Method.TABLE_CREATE,
  Method.TABLE_ADD_RESULTS,
  Method.PLAYLIST_PLAY,
  Method.PLAYLIST_STOP,
  Method.PLAYLIST_PLAY_SOUND,
  Method.MESSAGES_LIST,
  Method.DICE_ROLL_TO_CHAT,
  Method.DOCUMENTS_DUPLICATE,
  Method.PRESENT_SHOW,
  Method.PRESENT_PULL,
  Method.PRESENT_PING,
  Method.SCENE_UPDATE,
  Method.SCENE_RESET_FOG,
  Method.COMBAT_SET_INITIATIVE,
  Method.COMBAT_REMOVE,
  Method.MACRO_EXECUTE,
  Method.STATUS_GET,
  Method.CARDS_DEAL,
  Method.CARDS_DRAW,
  Method.CARDS_SHUFFLE,
  Method.CARDS_PASS,
  Method.CARDS_RESET,
  Method.TIME_ADVANCE,
  Method.TIME_SET,
  Method.WALLS_DRAW,
  Method.SCENE_CREATE,
  Method.DOOR_TOGGLE,
  Method.LIGHT_PLACE,
  Method.NOTE_PLACE,
  Method.TEMPLATE_PLACE,
  Method.DND5E_SPELL_SLOTS,
  Method.DND5E_CURRENCY,
  Method.DND5E_AWARD_XP,
  Method.DND5E_HIT_DICE,
  Method.DND5E_DEATH_SAVES,
  Method.DND5E_CONCENTRATION,
  Method.DND5E_USE_ITEM,
  Method.DND5E_ITEM_ROLL,
  Method.PLAYLIST_CREATE,
  Method.PLAYLIST_ADD_SOUNDS,
  Method.COMBATANT_DAMAGE,
  Method.COMBATANT_UPDATE,
  Method.COMBATANT_CONDITION,
  Method.MODULES_LIST,
  Method.MODULE_GET,
  Method.SETTINGS_LIST,
  Method.SETTING_GET,
  Method.SETTING_SET,
]);

export const PermissionTier = {
  READ: "read",
  WRITE: "write",
  DESTRUCTIVE: "destructive",
} as const;

export type PermissionTier = (typeof PermissionTier)[keyof typeof PermissionTier];

export const METHOD_TIERS: Record<Method, PermissionTier> = {
  [Method.PING]: PermissionTier.READ,
  [Method.WORLD_GET]: PermissionTier.READ,
  [Method.DOCUMENTS_LIST]: PermissionTier.READ,
  [Method.DOCUMENTS_GET]: PermissionTier.READ,
  [Method.DOCUMENTS_SEARCH]: PermissionTier.READ,
  [Method.DOCUMENTS_FIND_REFS]: PermissionTier.READ,
  [Method.DOCUMENTS_REFRESH_LABELS]: PermissionTier.WRITE,
  [Method.DOCUMENTS_CREATE]: PermissionTier.WRITE,
  [Method.DOCUMENTS_UPDATE]: PermissionTier.WRITE,
  [Method.FOLDERS_CREATE]: PermissionTier.WRITE,
  [Method.FOLDERS_MOVE]: PermissionTier.WRITE,
  [Method.EMBEDDED_CREATE]: PermissionTier.WRITE,
  [Method.EMBEDDED_UPDATE]: PermissionTier.WRITE,
  [Method.COMPENDIUM_LIST]: PermissionTier.READ,
  [Method.COMPENDIUM_SEARCH]: PermissionTier.READ,
  [Method.COMPENDIUM_IMPORT]: PermissionTier.WRITE,
  [Method.COMPENDIUM_EXPORT]: PermissionTier.WRITE,
  [Method.COMPENDIUM_CREATE]: PermissionTier.WRITE,
  [Method.MESSAGES_CREATE]: PermissionTier.WRITE,
  [Method.SCENE_ACTIVE]: PermissionTier.READ,
  [Method.SCENE_ACTIVATE]: PermissionTier.WRITE,
  [Method.TOKEN_PLACE]: PermissionTier.WRITE,
  [Method.TOKEN_UPDATE]: PermissionTier.WRITE,
  [Method.DICE_ROLL]: PermissionTier.READ,
  [Method.TABLE_DRAW]: PermissionTier.READ,
  [Method.COMBAT_CREATE]: PermissionTier.WRITE,
  [Method.COMBAT_ADD]: PermissionTier.WRITE,
  [Method.COMBAT_ROLL_INITIATIVE]: PermissionTier.WRITE,
  [Method.COMBAT_ADVANCE]: PermissionTier.WRITE,
  [Method.FILES_BROWSE]: PermissionTier.READ,
  [Method.FILES_UPLOAD]: PermissionTier.WRITE,
  [Method.ACTOR_CREATE]: PermissionTier.WRITE,
  [Method.ACTOR_GRANT_ITEM]: PermissionTier.WRITE,
  [Method.CONDITIONS_LIST]: PermissionTier.READ,
  [Method.ACTOR_TOGGLE_CONDITION]: PermissionTier.WRITE,
  [Method.ACTOR_ROLL_DATA]: PermissionTier.READ,
  [Method.ACTOR_ASSIGN]: PermissionTier.WRITE,
  [Method.ACTOR_APPLY_DAMAGE]: PermissionTier.WRITE,
  [Method.ACTOR_APPLY_HEALING]: PermissionTier.WRITE,
  [Method.DND5E_APPLY_DAMAGE]: PermissionTier.WRITE,
  [Method.DND5E_APPLY_HEALING]: PermissionTier.WRITE,
  [Method.DND5E_ROLL]: PermissionTier.WRITE,
  [Method.DND5E_REST]: PermissionTier.WRITE,
  [Method.DND5E_ACTOR_SUMMARY]: PermissionTier.READ,
  [Method.TABLE_CREATE]: PermissionTier.WRITE,
  [Method.TABLE_ADD_RESULTS]: PermissionTier.WRITE,
  [Method.PLAYLIST_PLAY]: PermissionTier.WRITE,
  [Method.PLAYLIST_STOP]: PermissionTier.WRITE,
  [Method.PLAYLIST_PLAY_SOUND]: PermissionTier.WRITE,
  [Method.MESSAGES_LIST]: PermissionTier.READ,
  [Method.DICE_ROLL_TO_CHAT]: PermissionTier.WRITE,
  [Method.DOCUMENTS_DUPLICATE]: PermissionTier.WRITE,
  [Method.PRESENT_SHOW]: PermissionTier.WRITE,
  [Method.PRESENT_PULL]: PermissionTier.WRITE,
  [Method.PRESENT_PING]: PermissionTier.WRITE,
  [Method.SCENE_UPDATE]: PermissionTier.WRITE,
  [Method.SCENE_RESET_FOG]: PermissionTier.WRITE,
  [Method.COMBAT_SET_INITIATIVE]: PermissionTier.WRITE,
  [Method.COMBAT_REMOVE]: PermissionTier.WRITE,
  [Method.STATUS_GET]: PermissionTier.READ,
  [Method.CARDS_DEAL]: PermissionTier.WRITE,
  [Method.CARDS_DRAW]: PermissionTier.WRITE,
  [Method.CARDS_SHUFFLE]: PermissionTier.WRITE,
  [Method.CARDS_PASS]: PermissionTier.WRITE,
  [Method.CARDS_RESET]: PermissionTier.WRITE,
  [Method.TIME_ADVANCE]: PermissionTier.WRITE,
  [Method.TIME_SET]: PermissionTier.WRITE,
  [Method.WALLS_DRAW]: PermissionTier.WRITE,
  [Method.SCENE_CREATE]: PermissionTier.WRITE,
  [Method.DOOR_TOGGLE]: PermissionTier.WRITE,
  [Method.LIGHT_PLACE]: PermissionTier.WRITE,
  [Method.NOTE_PLACE]: PermissionTier.WRITE,
  [Method.TEMPLATE_PLACE]: PermissionTier.WRITE,
  [Method.DND5E_SPELL_SLOTS]: PermissionTier.WRITE,
  [Method.DND5E_CURRENCY]: PermissionTier.WRITE,
  [Method.DND5E_AWARD_XP]: PermissionTier.WRITE,
  [Method.DND5E_HIT_DICE]: PermissionTier.WRITE,
  [Method.DND5E_DEATH_SAVES]: PermissionTier.WRITE,
  [Method.DND5E_CONCENTRATION]: PermissionTier.WRITE,
  [Method.DND5E_USE_ITEM]: PermissionTier.WRITE,
  [Method.DND5E_ITEM_ROLL]: PermissionTier.WRITE,
  [Method.PLAYLIST_CREATE]: PermissionTier.WRITE,
  [Method.PLAYLIST_ADD_SOUNDS]: PermissionTier.WRITE,
  [Method.COMBATANT_DAMAGE]: PermissionTier.WRITE,
  [Method.COMBATANT_UPDATE]: PermissionTier.WRITE,
  [Method.COMBATANT_CONDITION]: PermissionTier.WRITE,
  [Method.MODULES_LIST]: PermissionTier.READ,
  [Method.MODULE_GET]: PermissionTier.READ,
  [Method.SETTINGS_LIST]: PermissionTier.READ,
  [Method.SETTING_GET]: PermissionTier.READ,
  [Method.SETTING_SET]: PermissionTier.WRITE,
  [Method.DOCUMENTS_DELETE]: PermissionTier.DESTRUCTIVE,
  [Method.MACRO_EXECUTE]: PermissionTier.DESTRUCTIVE,
  [Method.EMBEDDED_DELETE]: PermissionTier.DESTRUCTIVE,
  [Method.COMPENDIUM_DELETE]: PermissionTier.DESTRUCTIVE,
};

const docRefSchema = z
  .object({
    _id: z.string().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
  })
  .refine((v) => v._id || v.id || v.name, {
    message: "Document reference requires _id, id, or name",
  });

const tableResultSchema = z.union([
  z.string().min(1),
  z.object({
    text: z.string().min(1),
    weight: z.number().int().positive().optional(),
  }),
]);

export const paramSchemas = {
  [Method.PING]: z.object({}).optional(),
  [Method.WORLD_GET]: z.object({}).optional(),
  [Method.DOCUMENTS_LIST]: z.object({
    collection: z.string().min(1),
    where: z.record(z.string(), z.unknown()).optional(),
    requested_fields: z.array(z.string()).optional(),
    sort: z.string().min(1).optional(),
    sort_dir: z.enum(["asc", "desc"]).optional(),
    offset: z.number().int().nonnegative().optional(),
    limit: z.number().int().positive().optional(),
    max_length: z.number().int().positive().optional(),
  }),
  [Method.DOCUMENTS_GET]: z.object({
    collection: z.string().min(1),
    ref: docRefSchema,
    requested_fields: z.array(z.string()).optional(),
  }),
  [Method.DOCUMENTS_SEARCH]: z.object({
    query: z.string().min(1),
    collections: z.array(z.string().min(1)).optional(),
    type: z.string().min(1).optional(),
    match_fields: z.array(z.string().min(1)).optional(),
    include_text: z.boolean().optional(),
    limit: z.number().int().positive().optional(),
  }),
  [Method.DOCUMENTS_FIND_REFS]: z.object({
    target: z.string().min(1),
    collections: z.array(z.string().min(1)).optional(),
    limit: z.number().int().positive().optional(),
  }),
  [Method.DOCUMENTS_REFRESH_LABELS]: z.object({
    target: z.string().min(1),
    dry_run: z.boolean().optional(),
  }),
  [Method.DOCUMENTS_CREATE]: z.object({
    type: z.string().min(1),
    data: z.array(z.record(z.string(), z.unknown())).min(1),
    dry_run: z.boolean().optional(),
  }),
  // `updates` entries are deep-merged; an optional `unset: string[]` (dotted
  // paths) on an entry removes keys (translated to Foundry's -= syntax).
  [Method.DOCUMENTS_UPDATE]: z.object({
    type: z.string().min(1),
    _id: z.string().min(1),
    updates: z.array(z.record(z.string(), z.unknown())).min(1),
    dry_run: z.boolean().optional(),
  }),
  [Method.DOCUMENTS_DELETE]: z.object({
    type: z.string().min(1),
    ids: z.array(z.string().min(1)).min(1),
    dry_run: z.boolean().optional(),
  }),
  [Method.EMBEDDED_CREATE]: z.object({
    parent_type: z.string().min(1),
    parent_id: z.string().min(1),
    embedded: z.string().min(1),
    data: z.array(z.record(z.string(), z.unknown())).min(1),
  }),
  [Method.EMBEDDED_UPDATE]: z.object({
    parent_type: z.string().min(1),
    parent_id: z.string().min(1),
    embedded: z.string().min(1),
    updates: z.array(z.record(z.string(), z.unknown())).min(1),
    dry_run: z.boolean().optional(),
  }),
  [Method.EMBEDDED_DELETE]: z.object({
    parent_type: z.string().min(1),
    parent_id: z.string().min(1),
    embedded: z.string().min(1),
    ids: z.array(z.string().min(1)).min(1),
    dry_run: z.boolean().optional(),
  }),
  [Method.COMPENDIUM_LIST]: z
    .object({ type: z.string().min(1).optional() })
    .optional(),
  [Method.COMPENDIUM_SEARCH]: z.object({
    pack: z.string().min(1),
    query: z.string().optional(),
    type: z.string().min(1).optional(),
    limit: z.number().int().positive().optional(),
  }),
  [Method.COMPENDIUM_IMPORT]: z.object({
    pack: z.string().min(1),
    entries: z.array(docRefSchema).min(1),
    folder: z.union([z.string().min(1), docRefSchema]).optional(),
  }),
  [Method.COMPENDIUM_EXPORT]: z.object({
    pack: z.string().min(1),
    type: z.string().min(1),
    entries: z.array(docRefSchema).min(1),
  }),
  [Method.COMPENDIUM_CREATE]: z.object({
    label: z.string().min(1),
    type: z.string().min(1),
  }),
  [Method.COMPENDIUM_DELETE]: z.object({
    pack: z.string().min(1),
  }),
  [Method.FOLDERS_CREATE]: z.object({
    type: z.string().min(1),
    name: z.string().min(1),
    parent: z.string().min(1).optional(),
  }),
  [Method.FOLDERS_MOVE]: z.object({
    type: z.string().min(1),
    entity: docRefSchema,
    folder: z.union([docRefSchema, z.null()]),
  }),
  [Method.MESSAGES_CREATE]: z.object({
    content: z.string().min(1),
    whisper: z.union([z.literal("gm"), z.array(docRefSchema)]).optional(),
    blind: z.boolean().optional(),
    speaker_alias: z.string().min(1).optional(),
  }),
  [Method.SCENE_ACTIVE]: z.object({}).optional(),
  [Method.SCENE_ACTIVATE]: z.object({ ref: docRefSchema }),
  [Method.TOKEN_PLACE]: z.object({
    scene: docRefSchema.optional(),
    actor: docRefSchema,
    x: z.number(),
    y: z.number(),
    hidden: z.boolean().optional(),
    name: z.string().min(1).optional(),
  }),
  [Method.TOKEN_UPDATE]: z.object({
    scene: docRefSchema.optional(),
    token_id: z.string().min(1),
    updates: z.record(z.string(), z.unknown()),
  }),
  [Method.DICE_ROLL]: z.object({
    formula: z.string().min(1),
    data: z.record(z.string(), z.unknown()).optional(),
  }),
  [Method.TABLE_DRAW]: z.object({
    ref: docRefSchema,
    formula: z.string().min(1).optional(),
  }),
  [Method.COMBAT_CREATE]: z.object({ scene: docRefSchema.optional() }),
  [Method.COMBAT_ADD]: z.object({
    combat: docRefSchema.optional(),
    tokens: z.array(z.string().min(1)).min(1),
    roll_initiative: z.boolean().optional(),
  }),
  [Method.COMBAT_ROLL_INITIATIVE]: z.object({
    combat: docRefSchema.optional(),
    combatants: z
      .union([z.literal("all"), z.array(z.string().min(1)).min(1)])
      .optional(),
  }),
  [Method.COMBAT_ADVANCE]: z.object({
    combat: docRefSchema.optional(),
    action: z.enum([
      "start",
      "next",
      "previous",
      "end",
      "next_round",
      "previous_round",
    ]),
  }),
  [Method.FILES_BROWSE]: z.object({
    target: z.string(),
    source: z.string().min(1).optional(),
    type: z.string().min(1).optional(),
  }),
  [Method.FILES_UPLOAD]: z.object({
    target: z.string(),
    filename: z.string().min(1),
    data_base64: z.string().min(1),
    source: z.string().min(1).optional(),
    content_type: z.string().min(1).optional(),
  }),
  [Method.ACTOR_CREATE]: z.object({
    name: z.string().min(1),
    type: z.string().min(1).optional(),
    folder: z.string().min(1).optional(),
    data: z.record(z.string(), z.unknown()).optional(),
  }),
  [Method.ACTOR_GRANT_ITEM]: z.object({
    actor: docRefSchema,
    pack: z.string().min(1).optional(),
    entry: docRefSchema.optional(),
    item: z.record(z.string(), z.unknown()).optional(),
  }),
  [Method.CONDITIONS_LIST]: z.object({}).optional(),
  [Method.ACTOR_TOGGLE_CONDITION]: z.object({
    actor: docRefSchema,
    condition: z.string().min(1),
    active: z.boolean().optional(),
  }),
  [Method.ACTOR_ROLL_DATA]: z.object({ actor: docRefSchema }),
  [Method.ACTOR_ASSIGN]: z.object({
    actor: docRefSchema,
    user: docRefSchema,
    level: z.number().int().min(0).max(3).optional(),
  }),
  [Method.ACTOR_APPLY_DAMAGE]: z.object({
    actor: docRefSchema,
    amount: z.number(),
  }),
  [Method.ACTOR_APPLY_HEALING]: z.object({
    actor: docRefSchema,
    amount: z.number(),
  }),
  [Method.DND5E_APPLY_DAMAGE]: z.object({
    actor: docRefSchema,
    amount: z.number(),
    type: z.string().min(1).optional(),
    multiplier: z.number().optional(),
  }),
  [Method.DND5E_APPLY_HEALING]: z.object({
    actor: docRefSchema,
    amount: z.number(),
    temp: z.boolean().optional(),
  }),
  [Method.DND5E_ROLL]: z.object({
    actor: docRefSchema,
    kind: z.enum(["save", "check", "skill", "death"]),
    key: z.string().min(1).optional(),
  }),
  [Method.DND5E_REST]: z.object({
    actor: docRefSchema,
    type: z.enum(["short", "long"]),
  }),
  [Method.DND5E_ACTOR_SUMMARY]: z.object({ actor: docRefSchema }),
  [Method.TABLE_CREATE]: z.object({
    name: z.string().min(1),
    folder: z.string().min(1).optional(),
    formula: z.string().min(1).optional(),
    results: z.array(tableResultSchema).optional(),
  }),
  [Method.TABLE_ADD_RESULTS]: z.object({
    table: docRefSchema,
    results: z.array(tableResultSchema).min(1),
  }),
  [Method.PLAYLIST_PLAY]: z.object({ playlist: docRefSchema }),
  [Method.PLAYLIST_STOP]: z.object({ playlist: docRefSchema }),
  [Method.PLAYLIST_PLAY_SOUND]: z.object({
    playlist: docRefSchema,
    sound: docRefSchema,
  }),
  [Method.MESSAGES_LIST]: z
    .object({ limit: z.number().int().positive().optional() })
    .optional(),
  [Method.DICE_ROLL_TO_CHAT]: z.object({
    formula: z.string().min(1),
    flavor: z.string().min(1).optional(),
    whisper: z.union([z.literal("gm"), z.array(docRefSchema)]).optional(),
  }),
  [Method.DOCUMENTS_DUPLICATE]: z.object({
    type: z.string().min(1),
    ref: docRefSchema,
    name: z.string().min(1).optional(),
    folder: z.string().min(1).optional(),
  }),
  [Method.PRESENT_SHOW]: z
    .object({
      image: z.string().min(1).optional(),
      journal: docRefSchema.optional(),
      title: z.string().min(1).optional(),
    })
    .refine((v) => v.image || v.journal, {
      message: "Provide `image` (a path) or `journal` (a reference)",
    }),
  [Method.PRESENT_PULL]: z.object({ scene: docRefSchema }),
  [Method.PRESENT_PING]: z.object({
    x: z.number(),
    y: z.number(),
    scene: docRefSchema.optional(),
  }),
  [Method.SCENE_UPDATE]: z.object({
    scene: docRefSchema.optional(),
    updates: z.record(z.string(), z.unknown()),
  }),
  [Method.SCENE_RESET_FOG]: z
    .object({ scene: docRefSchema.optional() })
    .optional(),
  [Method.COMBAT_SET_INITIATIVE]: z.object({
    combat: docRefSchema.optional(),
    combatant: z.string().min(1),
    value: z.number(),
  }),
  [Method.COMBAT_REMOVE]: z.object({
    combat: docRefSchema.optional(),
    combatants: z.array(z.string().min(1)).min(1),
  }),
  [Method.MACRO_EXECUTE]: z.object({
    macro: docRefSchema,
    args: z.record(z.string(), z.unknown()).optional(),
  }),
  [Method.STATUS_GET]: z.object({}).optional(),
  [Method.CARDS_DEAL]: z.object({
    deck: docRefSchema,
    to: z.array(docRefSchema).min(1),
    number: z.number().int().positive().optional(),
  }),
  [Method.CARDS_DRAW]: z.object({
    to: docRefSchema,
    from: docRefSchema,
    number: z.number().int().positive().optional(),
  }),
  [Method.CARDS_SHUFFLE]: z.object({ deck: docRefSchema }),
  [Method.CARDS_PASS]: z.object({
    from: docRefSchema,
    to: docRefSchema,
    cards: z.array(z.string().min(1)).min(1),
  }),
  [Method.CARDS_RESET]: z.object({ deck: docRefSchema }),
  [Method.TIME_ADVANCE]: z.object({ seconds: z.number().int() }),
  [Method.TIME_SET]: z.object({ worldTime: z.number().int().nonnegative() }),
  [Method.WALLS_DRAW]: z.object({
    scene: docRefSchema.optional(),
    segments: z
      .array(
        z.object({
          x1: z.number(),
          y1: z.number(),
          x2: z.number(),
          y2: z.number(),
          door: z.number().int().min(0).max(2).optional(),
          ds: z.number().int().min(0).max(2).optional(),
        }),
      )
      .min(1),
  }),
  [Method.SCENE_CREATE]: z.object({
    name: z.string().min(1),
    width: z.number().int().positive().optional(),
    height: z.number().int().positive().optional(),
    grid_size: z.number().int().positive().optional(),
    grid_type: z.number().int().min(0).max(5).optional(),
    padding: z.number().min(0).max(0.5).optional(),
    background: z.string().min(1).optional(),
    activate: z.boolean().optional(),
  }),
  [Method.DOOR_TOGGLE]: z.object({
    scene: docRefSchema.optional(),
    wall_id: z.string().min(1),
    state: z.number().int().min(0).max(2).optional(),
  }),
  [Method.LIGHT_PLACE]: z.object({
    scene: docRefSchema.optional(),
    x: z.number(),
    y: z.number(),
    dim: z.number().nonnegative().optional(),
    bright: z.number().nonnegative().optional(),
    color: z.string().min(1).optional(),
  }),
  [Method.NOTE_PLACE]: z.object({
    scene: docRefSchema.optional(),
    x: z.number(),
    y: z.number(),
    journal: docRefSchema,
    text: z.string().min(1).optional(),
    icon_size: z.number().int().positive().optional(),
  }),
  [Method.TEMPLATE_PLACE]: z.object({
    scene: docRefSchema.optional(),
    t: z.enum(["circle", "cone", "ray", "rect"]),
    x: z.number(),
    y: z.number(),
    distance: z.number().positive(),
    direction: z.number().optional(),
    angle: z.number().optional(),
    width: z.number().positive().optional(),
  }),
  [Method.DND5E_SPELL_SLOTS]: z.object({
    actor: docRefSchema,
    level: z.union([z.number().int().min(1).max(9), z.literal("pact")]),
    action: z.enum(["use", "recover", "set"]),
    amount: z.number().int().nonnegative().optional(),
  }),
  [Method.DND5E_CURRENCY]: z.object({
    actor: docRefSchema,
    mode: z.enum(["add", "set"]),
    changes: z
      .object({
        pp: z.number().int().optional(),
        gp: z.number().int().optional(),
        ep: z.number().int().optional(),
        sp: z.number().int().optional(),
        cp: z.number().int().optional(),
      })
      .refine((c) => Object.keys(c).length > 0, { message: "Provide at least one coin type" }),
  }),
  [Method.DND5E_AWARD_XP]: z.object({
    actor: docRefSchema,
    amount: z.number().int(),
  }),
  [Method.DND5E_HIT_DICE]: z.object({
    actor: docRefSchema,
    action: z.enum(["spend", "recover"]),
    amount: z.number().int().positive().optional(),
  }),
  [Method.DND5E_DEATH_SAVES]: z
    .object({
      actor: docRefSchema,
      successes: z.number().int().min(0).max(3).optional(),
      failures: z.number().int().min(0).max(3).optional(),
    })
    .refine((p) => p.successes !== undefined || p.failures !== undefined, {
      message: "Provide successes and/or failures",
    }),
  [Method.DND5E_CONCENTRATION]: z.object({
    actor: docRefSchema,
    action: z.enum(["check", "break"]),
  }),
  [Method.DND5E_USE_ITEM]: z.object({
    actor: docRefSchema,
    item: docRefSchema,
  }),
  [Method.DND5E_ITEM_ROLL]: z.object({
    actor: docRefSchema,
    item: docRefSchema,
    kind: z.enum(["attack", "damage"]),
  }),
  [Method.PLAYLIST_CREATE]: z.object({
    name: z.string().min(1),
    mode: z.number().int().min(-1).max(2).optional(),
    sounds: z
      .array(
        z.object({
          name: z.string().min(1),
          path: z.string().min(1),
          repeat: z.boolean().optional(),
          volume: z.number().min(0).max(1).optional(),
        }),
      )
      .optional(),
  }),
  [Method.PLAYLIST_ADD_SOUNDS]: z.object({
    playlist: docRefSchema,
    sounds: z
      .array(
        z.object({
          name: z.string().min(1),
          path: z.string().min(1),
          repeat: z.boolean().optional(),
          volume: z.number().min(0).max(1).optional(),
        }),
      )
      .min(1),
  }),
  [Method.COMBATANT_DAMAGE]: z.object({
    combat: docRefSchema.optional(),
    combatant: z.string().min(1),
    amount: z.number().int(),
    type: z.string().min(1).optional(),
  }),
  [Method.COMBATANT_UPDATE]: z
    .object({
      combat: docRefSchema.optional(),
      combatant: z.string().min(1),
      defeated: z.boolean().optional(),
      hidden: z.boolean().optional(),
      initiative: z.number().optional(),
    })
    .refine(
      (p) => p.defeated !== undefined || p.hidden !== undefined || p.initiative !== undefined,
      { message: "Provide at least one of defeated/hidden/initiative" },
    ),
  [Method.COMBATANT_CONDITION]: z.object({
    combat: docRefSchema.optional(),
    combatant: z.string().min(1),
    condition: z.string().min(1),
    active: z.boolean().optional(),
  }),
  [Method.MODULES_LIST]: z
    .object({
      active: z.boolean().optional(),
    })
    .optional(),
  [Method.MODULE_GET]: z.object({
    id: z.string().min(1),
  }),
  [Method.SETTINGS_LIST]: z
    .object({
      namespace: z.string().min(1).optional(),
      include_values: z.boolean().optional(),
    })
    .optional(),
  [Method.SETTING_GET]: z.object({
    namespace: z.string().min(1),
    key: z.string().min(1),
  }),
  [Method.SETTING_SET]: z.object({
    namespace: z.string().min(1),
    key: z.string().min(1),
    value: z.unknown(),
  }),
} as const satisfies Record<Method, z.ZodTypeAny>;

export type ParamsFor<M extends Method> = z.infer<(typeof paramSchemas)[M]>;
